import type { Metadata } from "next";
import "./globals.css";
import UseLenis from "./hooks/useLenis";
export const metadata: Metadata = {
  title: "McApline",
  icons: {
    icon: "/apple-touch-icon.png",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <UseLenis>{children}</UseLenis>
      </body>
    </html>
  );
}
